Fix/handle editor play mode state change
realitycollective/com.realitycollective.service-framework pull request #18
Opened 2022-06-21 16:49 UTC by SimonDarksideJ

# Reality Collective - Reality Toolkit Pull Request

## Overview

Fixes a VERY annoying issue whereby on entering Play Mode, Unity will run "Validate" and attempt to initialise the Service Manager. Where this is normally required for normal Unity Editing, this instance is then destroyed before "Awake" is called.
This fix "finally" allows the Service Manager to "skip" initialisation if the Unity Editor enters play mode and prevents double initialization.

Does not affect normal "Play" mode as this is an editor only behaviour.

Also fixed a minor grievance where the Service Manager for whatever reason is not initialised in the Editor and causes the inspector to throw a null reference exception (rare issue)

## Changes

- Implemented a "EditorPlayModeStateChange" editor flag, which is set on entering play mode in the editor and reset when it leaves.
- Fixed an edge case where Unity does NOT initialise the Service Framework in the editor that caused a null reference exception in the inspector.

## Breaking Changes

None

2022-06-21 16:54 UTC, FejZa requested changes

2022-06-21 16:54 UTC, FejZa commented on Editor/ServiceProfileInspector.cs
>                  //TODO
Can we get rid of this TODO comment?

2022-06-21 16:54 UTC, FejZa commented on Runtime/Utilities/ServiceFrameworkStatus.cs
> +namespace RealityCollective.ServiceFramework
This sounds like it should live in an Editor assembly

2022-06-21 16:54 UTC, FejZa commented on Runtime/Utilities/ServiceManagerInstance.cs
> +            var UnityEditorRunState = EditorPrefs.GetBool(ServiceFrameworkStatus.UnityEditorRunStateKey);
this needs to be camelCase

2022-06-21 16:57 UTC, SimonDarksideJ commented on Runtime/Utilities/ServiceFrameworkStatus.cs
> +namespace RealityCollective.ServiceFramework
Can't because it is needed in the runtime project :S  Unfortunately

2022-06-21 17:02 UTC, FejZa submitted a review, later dismissed

2022-06-21 17:31 UTC, merged

2022-06-22 23:44 UTC, SimonDarksideJ commented
Unbelievable, I think I found another edge case in the editor where it attempts to run both Validate and Awake at the same time.  Still need to test more, but on opening a scene when the editor loads.
Doesn't seem to happen if you just open a scene, just if your previous scene you had open when Unity closed, if unity actually reopens on the same scene, this issue can occur.