Fix getting services by their base type and add tests
realitycollective/com.realitycollective.service-framework pull request #31
Opened 2022-09-26 16:28 UTC by FejZa

# Reality Collective - Reality Toolkit Pull Request

## Overview

Fixed the existing or new (lord knows) issue that services could not be retrieved by their base interface type. Also adds a bunch of tests to test this specific use case.

## Changes

What I said above.

## Breaking Changes

None.

## Related Submodule Changes

None

## Testing status

Includes unit tests.

### Manual testing status

Tested and verified in custom project with increased complexity and many custom services and providers.

2022-09-27 10:15 UTC, SimonDarksideJ requested changes

2022-09-27 10:15 UTC, SimonDarksideJ commented on Runtime/Services/ServiceManager.cs
> +            foreach (var activeService in activeServices)
TryGetValue performs this same operation but in a safe context and also handles if "activeServices" is null which this does not.

Any reason to change this?
As far as I can see, this is just reordering the AssignableFrom and CheckService, so maybe just to that instead of switching to an unsafe foreach.

2022-09-27 10:15 UTC, SimonDarksideJ commented on Tests/TestData/Interfaces/ITestService.cs
> +    public interface ITestService : IService { }
If testing for the scenario of nested interfaces, I would have expected a few more test classes with that behaviour
E.G. 
TestService : MyServiceBase -> MyServiceBase : MyInterface -> MyInterface : IService

2022-09-27 10:19 UTC, FejZa commented on Runtime/Services/ServiceManager.cs
> +            foreach (var activeService in activeServices)
TryGetValue is nowhere the same as my change. Please take a look again what it does. TryGetValue will look for a specific value in the dictionary, which will obviously always return false for anything that is not in the dictionary. Whereas the new solution will ensure that interface inheritance is respected and return true, if the value in the dictionary is assignable for the requested interface type.

Without this change those tests and scenarios will fail, with the change things work as expected.

2022-09-27 10:20 UTC, FejZa commented on Runtime/Services/ServiceManager.cs
> +            foreach (var activeService in activeServices)
I don't see any null check there for activeServices. TryGetValue does not check, whether activeServices is null and would raise an NRE if it was. activeServices must never be null, that'd be a major design flaw.

2022-09-27 10:21 UTC, FejZa commented on Runtime/Services/ServiceManager.cs
> +            foreach (var activeService in activeServices)
The least is it supposed to be empty.

2022-09-27 10:21 UTC, FejZa commented on Runtime/Services/ServiceManager.cs
> +            foreach (var activeService in activeServices)
I don't feel like you took the time to understand what the change does tbh.

2022-10-01 11:08 UTC, SimonDarksideJ approved these changes

2022-10-01 11:08 UTC, merged